import React from 'react'
import AssociateMenu from '../../components/AssociateMenu'
import Head from 'next/head'
export default function Associate() {
  return (
    <>
    <Head>
        <title>Associate Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> 
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous"></link>
        
      </Head>
    <AssociateMenu></AssociateMenu>
    <div>Associate</div>
    </>
    
  )
}
